### ISSUE TITLE
RoR Nested Forms with Cocoon Gem Issue

### ISSUE THREAD

**Issue by beckybair** [beckybair/BexRecipeBox#1]
Issue:  I can't seem to figure out (or maybe not sure how to search for it on google).
It's with the nested forms:  it is like my form layout is backwards??  The Remove Ingredient button is first then the text box and then the label
I have it up live on Heroku so you can see what I'm talking about:  https://babs-recipe-box.herokuapp.com

Any help on pinpointing what I did wrong would be great!﻿

**Comment by beckybair** [comment]
Also - I created this following Mackenzie Child's youtube video here:  https://www.youtube.com/watch?v=QhdzE1yNs-0&index=3&list=PL23ZvcdS3XPLNdRYB_QyomQsShx59tpc-

I compared my code to his GitHub ( https://github.com/mackenziechild/recipe_box ) but couldn't find the difference other than the changes I made that "shouldn't" have caused this issue...

**Comment by beckybair** [comment]
The following gems are used:
gem 'simple_form', '~> 3.4'
gem 'bootstrap-sass', '~> 3.3', '>= 3.3.7'
gem 'paperclip', '~> 5.1'
gem 'aws-sdk', '~>2.3'
gem 'cocoon', '~> 1.2.6', '>= 1.2.9'
gem 'devise', '~> 4.3.0'
gem 'omniauth-facebook'
gem 'figaro'

**Comment by CouchofTomato** [comment]
.form_input and .form_button have float:left in the css which pushes them left of the label

**Comment by jjculber** [comment]
https://github.com/beckybair/BexRecipeBox/pull/2

**Comment by beckybair** [comment]
Great!  I'll check these when I get home and let you both know!

**Comment by beckybair** [comment]
Thank you both - @jjculber I accepted both your pull requests I believe.  Let me know if I didn't.  This is my first time with someone else contributing.
